"""empty message

Revision ID: b99629cb65d4
Revises: 10841bb4b0ea
Create Date: 2018-07-27 02:33:57.295317

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b99629cb65d4'
down_revision = '10841bb4b0ea'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_topics', sa.Column('_system_image_url', sa.String(), nullable=True))
    op.drop_column('event_topics', 'system_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_topics', sa.Column('system_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event_topics', '_system_image_url')
    # ### end Alembic commands ###
